name: Deploy to WP Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3.2.9
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE_FRESH }}
          WPE_ENV: scorerstabldev
